# Do not modify this file!  It was generated by ‘nixos-geneate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
#      ../hardware-configuration.nix
      ../users.nix
      ../services.nix
      ../nix.nix
      ../programs.nix
      ../networking.nix
      ../fonts.nix
      ../wayland.nix
      ../audio.nix
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
 
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.zfs.requestEncryptionCredentials = true;
  boot.zfs.enableUnstable = true;

  fileSystems."/" =
    { device = "gene/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "gene/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "gene/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E3F5-7052";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
  hardware.nvidia = {
   modesetting.enable = true;
  };
  time.timeZone = "America/Phoenix";
  system.stateVersion = "20.09";
}
